on: 
  push:
  workflow_dispatch:

env:
  VarX: hello
  VarY: true
  DKAV: "Inital_value"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    name: A job to say hello
    steps:
      - run: |
          env
        name: env disp ${{ env.DKAV }}
      - name: Hello world action step
        id: hello
        uses: dhanesh012/hello-world-javascript-action@main
        with:
          who-to-greet: 'dhan'
      # Use the output from the `hello` step
      - name: Get the output time ${{ env.DKAV }}
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The value is ${{ env.DKAV }}"
          echo "The value is ${{ env.VarY }}"
      - run: |
          env
        name: env disp ${{ env.VarY }}
      - name: echos
        run: |
          if [[ "${{ secrets.abc }}" == "BOB" ]]; then echo "......B.O.B"; else echo "...b.o.b"; fi
          echo "Hi ${{ secrets.abc }}"
          echo "Hi ${{ secrets.ABC }}"
          echo "Hi ${{ secrets.cde }}"
  hello_windos_job:
    runs-on: windows-latest
    steps:
    - run: |
        env
  hello_linux_job:
    runs-on: ubuntu-latest
    needs: hello_windos_job
    steps:
    - run: |
        env        
        
        
