on: 
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
      
env:
  VarX: hello
  VarY: true
  DKAV: "Inital_value"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    environment: dev
    name: A job to say hello
    steps:
      - run: az --version
#       - name: 'Az CLI login'
#         uses: azure/login@v1
#         with:
#             client-id: ${{ secrets.AZURE_CLIENT_ID }}
#             tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#             subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure CLI commands'
        run: |
            az account show
            az group list
            pwd 
      - run: |
          env
        name: env disp ${{ env.DKAV }}
      - name: Hello world action step
        id: hello
        uses: dhanesh012/hello-world-javascript-action@main
        with:
          who-to-greet: 'dhan'
          creds: ${{ secrets.DEV_SP }}
      # Use the output from the `hello` step
      - name: Get the output time ${{ env.DKAV }}
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The value is ${{ env.DKAV }}"
          echo "The value is ${{ env.VarY }}"
      - run: |
          env
        name: env disp ${{ env.VarY }}
      - name: echos
        run: |
          if [[ "${{ secrets.abc }}" == "BOB" ]]; then echo "......B.O.B"; else echo "...b.o.b"; fi
          echo "Hi ${{ secrets.abc }}"
          echo "Hi ${{ secrets.ABC }}"
          echo "Hi ${{ secrets.cde }}"
  hello_windos_job:
    runs-on: windows-latest
    steps:
    - run: |
        env
        
        
